services:
  app-server:
    container_name: server
    build:
      context: backend
    networks:
      - backend
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://db:$MYSQLDB_LOCAL_PORT/$MYSQLDB_DATABASE",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
    depends_on:
      - db
    stdin_open: true
    tty: true

  app-client:
    container_name: client
    build:
      context: frontend
    depends_on:
      - db
      - app-server

  db:
    container_name: database
    image: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:3306

volumes:
  db-data:
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
